Category list
marchi-martius/FreemarketRn pull request #1
Opened 2017-04-26 23:15 UTC by obliviusm

- add static list of Categories
- add list to state
- pass chosen category to products list

2017-04-27 09:05 UTC, marchi-martius requested changes
Please take a look at my comments.

2017-04-27 09:05 UTC, marchi-martius commented on index.android.js
> +	      <Text>Categories</Text>
Please move whole stuff from here to new container.

2017-04-27 09:05 UTC, marchi-martius commented on index.android.js
> +      	<ProductsList category={Categories[this.state.categoryIndex]} />
`category={this.currentCategory}`

2017-04-27 09:05 UTC, marchi-martius commented on index.android.js
> +]
Please move to external constants file

2017-04-27 09:05 UTC, marchi-martius commented on index.android.js
> +  }
Whole stuff should be encapsulated in container.

2017-04-27 23:15 UTC, obliviusm commented
@marchi-martius moved some stuff. not sure if i can move `onPressCategory`

2017-04-28 06:24 UTC, marchi-martius commented
@obliviusm please add tests

2017-05-03 11:44 UTC, marchi-martius approved these changes

2017-05-03 11:44 UTC, merged