Category Header implementation
marchi-martius/FreemarketRn pull request #23
Opened 2017-05-05 15:24 UTC by marchi-martius

2017-05-06 11:59 UTC, obliviusm requested changes
also i got this warning in tests:
```
Warning: Failed prop type: The prop `category` is marked as required in `CategoryHeader`, but its value is `undefined`.
          in CategoryHeader (created by Main)
          in Main (created by FreemarketRn)
          in Provider (created by App)
          in App (created by FreemarketRn)
          in FreemarketRn
```
could you fix that?

2017-05-06 11:59 UTC, obliviusm commented on app/components/CategoryOverviewView.js
> +    {Children.map(children, child => cloneElement(child, { category }))}
looks quite complicated and implicit. I hadn't known where `CategoryHeader` gets `category` from until i found this piece.

2017-05-06 12:00 UTC, obliviusm commented on app/components/CategoryOverviewView.js
> +    {Children.map(children, child => cloneElement(child, { category }))}
can you explain me why we need to do it this way and not with simple `<CategoryHeader {category=category}/>`?

2017-05-06 12:10 UTC, obliviusm commented
BTW header looks cool

2017-05-06 16:06 UTC, marchi-martius commented on app/components/CategoryOverviewView.js
> +    {Children.map(children, child => cloneElement(child, { category }))}
My intent was to make platform-independent component which can be used to retrieve current category (and products etc) and pass it as props to platform-specific components (header, list, footer). 
I don't particularly like my solution either. I'll rework it simpler.

2017-05-07 07:54 UTC, marchi-martius commented
@obliviusm fixed, please check out.

2017-05-07 11:00 UTC, obliviusm approved these changes

2017-05-07 11:04 UTC, obliviusm commented
Cool. Looks better to me
1. I reverted react-native upgrade. hope you don't mind. reason: sometimes i get blank screen when run project in this branch. i believe upgrade is the problem.
2. FYI i'm working on this right now: https://github.com/marchi-martius/FreemarketRn/issues/21

2017-05-07 11:04 UTC, merged