Product list
marchi-martius/FreemarketRn pull request #25
Opened 2017-05-12 23:30 UTC by obliviusm

https://github.com/marchi-martius/FreemarketRn/issues/17

2017-05-12 23:32 UTC, obliviusm commented
![screenshot_1494631846](https://cloud.githubusercontent.com/assets/1386397/26020190/5d6ad6bc-3784-11e7-92fb-25d064204fa4.png)

2017-05-12 23:32 UTC, obliviusm commented
WIP. only UI.
working on server-redux thing

2017-05-15 06:51 UTC, marchi-martius requested changes

2017-05-15 06:51 UTC, marchi-martius commented on app/components/CategoryOverviewView.js
> +import ProductList from '../containers/ProductList';
Please avoid such hierarchy (pulling containers from other's container's component - view).
We should move all `ProductList` mapping to `CategoryOverview` and pass props downstream.

2017-05-15 06:51 UTC, marchi-martius commented on app/components/__tests__/CategoryOverviewView.js
> +    <Provider store={store}>
My suggestion above will simplify such cases. BTW components should know nothing about store.

2017-05-15 06:51 UTC, marchi-martius commented on app/containers/ProductList.js
> +export default connect(mapStateToProps, mapDispatchToProps)(ProductListView);
Take a look at my comments above about this container.

2017-05-15 06:51 UTC, marchi-martius commented on app/sagas/products.js
> +}
We should extract code duplication for fetching API. I'll open an Issue for this.

2017-05-15 07:14 UTC, marchi-martius commented on app/sagas/products.js
> +}
#26

2017-05-15 10:27 UTC, obliviusm commented on app/components/CategoryOverviewView.js
> +import ProductList from '../containers/ProductList';
@marchi-martius I see your point. But now I think that `CategoryOverviewView` doesn't give any UI. We just need it to hold next containers. So I would rather move mapping below `CategoryOverviewView`, not above.

2017-05-15 13:43 UTC, obliviusm commented
@marchi-martius please, take look
Removed `CategoryOverview` for now.
Simplified platform code by https://facebook.github.io/react-native/docs/platform-specific-code.html#platform-specific-extensions

2017-05-16 13:13 UTC, marchi-martius approved these changes

2017-05-16 13:13 UTC, merged